[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "streamlit==1.51.0",
    "pandas==2.3.3",
    "plotly==6.5.0",
    "openpyxl==3.1.5"
]

[tool.streamlit]
main = "dashboard.py"
